stages:
  model_building:
    cmd: python src/model_building.py
    deps:
    - src/data/processed
    - src/model_building.py
    outs:
    - model.pkl
  model_evaluation:
    cmd: python src/model_eval.py
    deps:
    - model.pkl
    - src/model_eval.py
    metrics:
    - metrics.json
